services:
  # Backend #
  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui:latest
    container_name: iter_swagger_ui
    environment:
      SWAGGER_JSON: /swagger-ui/specification.yml
    ports:
      - 81:8080
    networks:
      - public_network
    volumes:
      - ./open-api/docs/specification.yml:/swagger-ui/specification.yml

  open-dpp-api:
    build: ./open-api
    container_name: open_dpp_api
    environment:
      ITER_DATABASE_URL: postgresql://iter-user:iter-password@open-dpp-db-slave:5432/db-iter-open

    ports:
      - 80:7000
    networks:
      - internal_network
      - public_network
    depends_on:
      open-dpp-db-slave:
        condition: service_healthy

  open-dpp-db-main:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    container_name: open_dpp_db_main
    environment:
      POSTGRESQL_PGAUDIT_LOG: READ,WRITE
      POSTGRESQL_LOG_HOSTNAME: true
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      POSTGRESQL_USERNAME: iter-user
      POSTGRESQL_PASSWORD: iter-password
      POSTGRESQL_DATABASE: db-iter-open
    networks:
      - internal_network
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - open_dpp_pg:/bitnami/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U iter-user -d db-iter-open']
      interval: 5s
      timeout: 5s
      retries: 5

  open-dpp-db-slave:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    container_name: open_dpp_db_slave
    environment:
      POSTGRESQL_USERNAME: iter-user
      POSTGRESQL_PASSWORD: iter-password
      POSTGRESQL_MASTER_HOST: open-dpp-db-main
      POSTGRESQL_PGAUDIT_LOG: READ,WRITE
      POSTGRESQL_LOG_HOSTNAME: true
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
    networks:
      - internal_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U iter-user -d db-iter-open']
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      open-dpp-db-main:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - 82:8080
    networks:
      - internal_network

  # Frontend #
  open-dpp-front:
    build:
      context: ./open-front
      args:
        VITE_OPEN_API_URL: http://localhost:80
    container_name: open_dpp_front
    ports:
      - 8080:80
    networks:
      - public_network
    depends_on:
      open-dpp-api:
        condition: service_started
networks:
  internal_network:
    driver: bridge
  public_network:
    external: true

# Compose volumes
volumes:
  open_dpp_pg:
